[package]
name = "cryptology"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
cli.workspace = true
workspace = { version = "0.1", path = "../workspace" }
